const express = require('express');
const cookieParser = require('cookie-parser');
const UserRoutes = require('./routes/UserRoutes');
const CategoryRoutes = require('./routes/categoryRoutes');
const ProductRoutes = require('./routes/ProductRoutes');
const OrderRoutes = require('./routes/OrderRoutes');
const CartRoutes = require('./routes/CartRoutes');
const ReviewRoutes = require('./routes/ReviewRoutes');
const AdminRoutes = require('./routes/AdminRoutes');
const { notFound, errorHandler } = require('./middleware/error');
const { securityHeaders, cors, rateLimit } = require('./middleware/security');

const app = express();
app.disable('x-powered-by');
app.set('trust proxy', process.env.TRUST_PROXY === 'true');
app.use(securityHeaders);
app.use(cors);
app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 300 }));
app.use(express.json({ limit: '100kb' }));
app.use(cookieParser());
app.get('/health', (req, res) => res.status(200).json({ status: 'ok' }));
app.use('/user', UserRoutes);
app.use('/category', CategoryRoutes);
app.use('/products', ProductRoutes);
app.use('/orders', OrderRoutes);
app.use('/cart', CartRoutes);
app.use('/reviews', ReviewRoutes);
app.use('/admin', AdminRoutes);
app.use(notFound);
app.use(errorHandler);
module.exports = app;
