const mongoose = require('mongoose');
const Review = require('../models/reviewM');
const Product = require('../models/productM');
const Order = require('../models/orderM');

async function refreshProductRating(productId) {
  const [result] = await Review.aggregate([{ $match: { product: new mongoose.Types.ObjectId(productId) } }, { $group: { _id: '$product', average: { $avg: '$rating' }, count: { $sum: 1 } } }]);
  await Product.findByIdAndUpdate(productId, { ratingAverage: result ? Math.round(result.average * 10) / 10 : 0, ratingCount: result ? result.count : 0 });
}
async function getProductReviews(req, res, next) { if (!mongoose.Types.ObjectId.isValid(req.params.productId)) return res.status(400).json({ message: 'Invalid product id' }); try { const page = Math.max(Number.parseInt(req.query.page, 10) || 1, 1); const limit = Math.min(Math.max(Number.parseInt(req.query.limit, 10) || 20, 1), 100); const filter = { product: req.params.productId }; const [reviews, total] = await Promise.all([Review.find(filter).populate('user', 'name').sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit), Review.countDocuments(filter)]); res.json({ reviews, pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); } catch (error) { next(error); } }
async function createReview(req, res, next) { try { const { productId, rating, title, comment } = req.body; const [product, deliveredOrder] = await Promise.all([Product.findById(productId), Order.exists({ user: req.user.id, status: 'delivered', 'items.product': productId })]); if (!product) return res.status(404).json({ message: 'Product not found' }); if (!deliveredOrder) return res.status(403).json({ message: 'Only customers with a delivered order can review this product' }); const review = await Review.create({ user: req.user.id, product: productId, rating, title, comment, verifiedPurchase: true }); await refreshProductRating(productId); res.status(201).json(review); } catch (error) { next(error); } }
async function updateReview(req, res, next) { if (!mongoose.Types.ObjectId.isValid(req.params.id)) return res.status(400).json({ message: 'Invalid review id' }); try { const review = await Review.findOneAndUpdate({ _id: req.params.id, user: req.user.id }, req.body, { new: true, runValidators: true }); if (!review) return res.status(404).json({ message: 'Review not found' }); await refreshProductRating(review.product); res.json(review); } catch (error) { next(error); } }
async function deleteReview(req, res, next) { if (!mongoose.Types.ObjectId.isValid(req.params.id)) return res.status(400).json({ message: 'Invalid review id' }); try { const review = await Review.findOneAndDelete({ _id: req.params.id, user: req.user.id }); if (!review) return res.status(404).json({ message: 'Review not found' }); await refreshProductRating(review.product); res.status(204).send(); } catch (error) { next(error); } }
module.exports = { getProductReviews, createReview, updateReview, deleteReview };
